---
title: "RWorksheet2"
output: html_document
date: "2023-10-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "RWorksheet_Sabio#2.rmd"
output: html_document
date: "2023-10-04"
---

```{r 1a}
operatorVec <- c(-5:5)
operatorVec
# the output arrange in ascending order.
```
```{r 1b}
x1<- 1:7
x1
```
```{r 2a}
Vec<- seq(1,3,0.2)
Vec
```
```{r 3}
age <- list(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,18.)
age
```
```{r 3a}
age[3]
```
```{r 3b}
workerAge <- age[c(2,4)]
workerAge
```
```{r 3c}
workerAge1 <- age[-c(4,12)]
workerAge1
```
```{r 4}
x <- c("first" = 3, "second" = 0, "third" = 9)
print(x)
```
```{r 4a}
selectedE <- x[c("first", "third")]
print(selectedE)
# It selectively accesses and displays the elements "first" and "third" from the vector, showing their corresponding values.
```
```{r 5}
x2<- c(-3:2)
x2
# Instead of -2 in the second element it changed into 0.
```
```{r 5a}
x2[2] <- 0
x2
```
```{r 6a}
month <- c("Jan", "Feb", "March", "Apr", "May", "June")
price_per_liter <- c(52.50,57.25,60.00,65.00,74.25,54.00)
purchase_quantity <- c(25,30,40,50,10,45)
data.frame <- data.frame(month,  price_per_liter,  purchase_quantity)
data.frame
```
```{r 6b}
weighted.mean(price_per_liter,purchase_quantity)
```
```{r 7}
rivers
```
```{r 7c}
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),sd(rivers), min(rivers), max(rivers))
data
```
```{r 8a}
power_ranking <- c(1:25)
celebtrity_names <-c("Tom Cruise", "Rolling Stone", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", 
"Cast of Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas","Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay   Lenon", "Celine Dion", "Kobe Bryant" )
pay <- c(67,90,225,110,90,332,302,41,52,88,55,44,55,40,233,34,40,47,75,25,39,45,32,40,31)
PowerRanking <- data.frame(power_ranking, celebtrity_names, pay)
PowerRanking
```
```{r 8b}
power_ranking[19] <- 15
power_ranking 
pay[19] <- 90
pay
```
```{r 8c}
installed.packages("writexl")
library(writexl)
write_xlsx(PowerRanking, path = "PowerRanking.xlsx")
write.csv(PowerRanking, file = "PowerRanking.csv", row.names = FALSE)
```
```{r 8d}
subset_data <- PowerRanking[10:20, ]
save(subset_data, file = "Ranks.RData")
print(subset_data)
```
```{r 9a}
install.packages("readxl")
library(readxl)
hotelsVienna <- read_excel("hotels-vienna.xlsx")
# View(hotelsVienna)
hotelsVienna
```
```{r 9b}
dimensions <- dim(hotelsVienna)
dimensions
```
```{r 9c}
selected_columns <- hotelsVienna[, c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
head(selected_columns, n = nrow(selected_columns))
```
```{r 9d}
save(selected_columns, file = "new.RData")
```

```{r 9e}
load("new.RData")
head(selected_columns)
tail(selected_columns)
```
```{r 10a}
Vegetables <- list("carrots","potato","eggplant","potato", "broccoli", "tomato", "onion", "seaweed","cabbage","corn")
Vegetables
```
```{r 10b}
vegetablesList <- append(Vegetables,c("spinach","green beans"),after=10)
vegetablesList
```
```{r 10c}
Veggies <- append(vegetablesList,c("Cauliflower","Sprouts","Kale","Sweet Potatos"),after=5)
Veggies
```
```{r 10d}
NewVeggies<- Veggies[c(-5,-10,-15)]
NewVeggies

length(NewVeggies)
```

