---
title: "RWorksheet_SABIO#4a.Rmd"
output: pdf_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Number 1:
```{r 1} 
install.packages("readxl")
library(readxl)
HouseholdData <- read_excel("Household Data.xlsx")
# View(HouseholdData)
HouseholdData 
```
a.
```{r 1a}
#The data shows the gender,height and shoe size.
```
b.
```{r 1b}
# Create a sample data frame
data <- data.frame(
  Gender = c("F","F","F","F","M", "F","F","F", "M", "F","M","F","M","M", "M","M", "F","F","M","F","F","M","M","F", "M","M","M","M")
)
males <- subset(data, Gender == "M")
males
females <- subset(data, Gender == "F")
females

```
c.
```{r 1c}
mean(HouseholdData$`Shoe Size`)
mean(HouseholdData$Height...2)
```
d
```{r 1d}
#yes,because a person with a taller height may have a larger shoe size on average.
```
Number 2:
```{r 2}
months_vector <- c("March","April","January","November","January",
"September","October","September","November","August",
"January","November","November","February","May","August","July","December","August","August","September","November","February",
"April")
 factor_months_vector <- factor(months_vector)
print( factor_months_vector)
```
Number 3:
```{r 3}
summary(months_vector)

summary(factor_months_vector)
# the result of summary of months_vector it provides information on 
#the counts of each month in the character vector it is useful when 
#understanding the distribution of month names in original data. In 
#factor_months_vector gives you the same information but represented 
#as counts of factor levels it is useful when you want to work with 
#categorical data and perform operation depend on factor levels. 
```
Number 4:
```{r 4}
factor_data<- c("East","West","West","North","North","North","North")
new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)
```
Numebr 5:
```{r 5}
student_table <- read.table(file = 'import_march.csv', header = TRUE, sep = ',')
student_table
```
Number 6:
```{r 6}
num <- readline(prompt="Enter a number from 1 to 50: ")
if (num >= 1 && num <= 50) {
  if (user_input == 20) {
    print("TRUE")
  } else {
    print(user_input)
  }
} else {
  print("The number selected is beyond the range of 1 to 50")
}
```
Number 7:
```{r 7}
calcMin_Bills<- function(){
  price<- as.integer(readline(prompt = "Price of snack(a random number divicible by 50):"))
  
  if (is.na(price)||price %% 50!=0){
    cat("Invalid input.Please enter a valid price divisible by 50.\n")
    return()
  }
  
  numBills<- 0
  bill<- c(1000,500,200,100,50)
  
  for(bill in bill){
    numBills<-numBills+(price %% bill)
    price<- price%%bill
  }
  cat("Minimum number of bills needed:",numBills,"\n")
}

calcMin_Bills()
```
Number 8:
```{r 8a}
name<- c("Annie","Thea","Steve","Hanna")
grade1<- c(85,65,75,95)
grade2<- c(65,75,55,75)
grade3<- c(85,90,80,100)
grade4<- c(95,75,100,90)
card<- data.frame(name,grade1,grade2,grade3,grade4)
card
```

b
```{r 8b}
for (i in 1:length(name)) {
  averageScore <- (grade1[i] + grade2[i] + grade3[i] + grade4[i]) / 4
  cat(paste(name[i], "'s average grade this semester is ", round(averageScore, 2), ".\n"))
}
```

c
```{r 8c}
for (testNum in 1:4){
  totalScore<- grade1 + grade2 + grade3 + grade4
  averageScore<- totalScore/4

if (averageScore[testNum]<80){
  cat("The",testNum,"test was difficult.\n")
}
}
```

d
```{r 8d}
for (i in 1:length(name)){
  highestGrade<- grade1[i]

  if (grade2[i]>highestGrade){
    highestGrade<- grade2[i]
  }
  if (grade3[i]>highestGrade){
    highestGrade<- grade3[i]
  }
  if (grade4[i]>highestGrade){
    highestGrade<- grade4[i]
  }
  if (highestGrade>90){
    cat(paste(name[i],"'s higest grade this semester is", highestGrade, ".\n"))
  }
}
```
  