---
title: "RWorksheet3A.rmd"
output: pdf_document
date: "2023-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 1}
LETTERS<- c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z")
LETTERS

letters<- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r" ,"s", "t", "u", "v", "w", "x", "y", "z")
letters
```
```{r 1a}
head(LETTERS,11)
```
```{r 1b}
indices <- c(1,3,5,7,9,11,13,15,17,19,21,23,25)
oddNumLetters <- LETTERS[indices]
print(oddNumLetters)
```
```{r 1c}
indices<- c(1,5,9,15,21)
selectedE<-LETTERS[indices]
print(selectedE)
```
```{r 1d}
tail(letters,5)
```
```{r 1e}
indeces<- c(16:23)
LetterBetween<-letters[indices]
print(LetterBetween)
```
```{r 2a}
city <- c("Tuguegarao City","Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city
```
```{r 2b}
temp <- c("42","39", "34", '34', "30", "27")
temp
```
```{r 2}
AprilAveTemp <- data.frame (
  city = c("Tuguegarao City", "Manila", "Iloilo", "Tacloban", "Samal Island", "Davao City"),
  temp = c(42, 39, 34, 34, 30, 27)  
)
str(AprilAveTemp)

colnames(AprilAveTemp)<- c("City", "Temperature")

print(AprilAveTemp)
#View(AprilAveTemp)
```
```{r 2f}
rows<-AprilAveTemp[c(3,4),]
rows
```
```{r 2g}
AprilAveTemp <- city

highestTemp <- max(AprilAveTemp)
highestTemp

lowestTemp <- min(AprilAveTemp)
lowestTemp
```
```{r 3a}
# Using Matrix
FMat<-matrix(c(1:8,11:14), ncol=4, nrow=3)  
FMat
```
```{r 3b}
SMat <- (FMat * 2)
SMat
```
```{r 3c}
row2 <- SMat[2, ]
row2
```
```{r 3d}
colRow <- SMat[1:2,3:4]
colRow
```
```{r 3e}
colRow1 <- SMat[3,2:3]
colRow1
```
```{r 3f}
col4 <- SMat[ ,4]
col4
```
```{r 3g}
colnames(SMat) <- c("uno","dos","tres","quatro")
rownames(SMat) <- c("isa","dalawa","tatlo")
print(SMat)
```
```{r 3h}
dim(FMat) <- c(6, 2)
FMat
```
```{r 4}
# Using Arrays
mArray<- array(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1))
mArray
```
```{r 4a}
repA <- rep(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1), each = 2)
repA
```
```{r 4a with dim}
threeD <- array(repA, dim = c(2, 4, 3))
threeD
```
```{r 4b}
dim(threeD)
```
```{r 4c}
dimnames(threeD) <- list(c("a", "b"), c("A", "B", "C", "D"), c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array"))
print(threeD)
```